### ISSUE TITLE
Huge bug // suggestions

### ISSUE THREAD

**Issue by jaylac2000** [Heisenburger69/SellWands#2]
Bug: 

I know this was reported already in #1 but also adding more suggestions to make it a better plugin

On a skyblock server you can use to sell on anyone's island which is a huge problem. you are gonna have to add in a feature so no one can use it in protected areas / zones / worlds if they dont have permissions to do anything there

3 Suggestions : 

1. 

Make it so you can edit messages in config with color 

ItemName: "&aSell Wand"
ItemLore: "&7Tap on a Chest to use"
NoSellableItems: "&cThere are no items to sell in this Chest"
SoldChest: "&a&lSuccess! &r&7sold the contents of the Chest for ยง8\${MONEY}"

^^ Thats all base off the current code except you cant color coat the first 3 in the code (at least i cant figure it out...)

2. 

Add 2 more messages 

GivenSellWand: "&7You have given {player} a sellwand"
ReceivedSellWand:  "&7You have received a sellwand"

3. 

Also add in config what the sell wand item should be either by using the item name or id or either way

**Comment by iZeaoGamer** [comment]
Hey. You can grab this Pull request build which should fix your issue.
Download it here: https://poggit.pmmp.io/r/76541/SellWands_pr-1.phar

**Comment by jaylac2000** [comment]
Thank you @iZeaoGamer

**Comment by jaylac2000** [comment]
add ally for /sellwand and make it /sw

**Comment by varunbln** [comment]
Added in latest commit
