### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaylac2000** [Heisenburger69/SellWands#5]
When you try and do certain things even without a sellwand in ur inv it says you cant use a sell wand (basically the sell-wand-cant-use-here-message message) 

If you want to see what I mean I can give you these items its doing it with on my server for example spawners. 
i can dm ip & port on discord. jay_lac2000#5648

**Comment by varunbln** [comment]
Should be fixed in latest commit

**Comment by jaylac2000** [comment]
thank you, sir!
