### ISSUE TITLE
Sign

### ISSUE THREAD

**Issue by DragaoNinja** [Heisenburger69/SellWands#6]
Hello good evening I would like to report a problem I have a minecraft server with a sign shop plugin  when I go to shop it seems "You cannot use sell wands here!" without me having the wand in hand thank you for your attention solving this soon :)

**Comment by varunbln** [comment]
Please use the latest build rather than the release which resolves this issue. Can be found at [download](https://poggit.pmmp.io/r/79167/SellWands_dev-11.phar)
