### ISSUE TITLE
Doesn't Work for People

### ISSUE THREAD

**Issue by FireWolf153** [Heisenburger69/SellWands#7]
Hi there.
I am trying to use this plugin on my server, but whenever my players try to click the sell wand on a chest, it says
![image](https://user-images.githubusercontent.com/67765275/98447783-2f6de000-20ed-11eb-884e-07abca46db27.png)
I have tried giving players the sellwand.use permission, but it still does not work.

**Comment by varunbln** [comment]
This is most likely caused due to some area management plugin disabling interaction permissions for players. Please try on a clean server(no other plugins) and reopen the issue if it still occurs
